//
//  main.c
//  lzy_5.11
//
//  Created by 赖志懿 on 15/4/22.
//  Copyright (c) 2015年 Lteam.lzy. All rights reserved.
//

#include <stdio.h>

void hailstone(int n);

int main(void) {
    int n;
    printf("Please input a number : ");
    scanf("%d",&n);
    printf("\nHailstone generated by %d\n",n);
    
    hailstone(n);
    
    return 0;
}

void hailstone(int n){
    int count=0;
    for (; n!=1; ) {
            switch (n%2) {
        case 1:
            printf("%5d",n);
            n=3*n+1;
            count++;
            if (count%6==0) printf("\n");
            break;
        case 0:
            printf("%5d",n);
            n/=2;
            count++;
            if (count%6==0) printf("\n");
            break;
        default:
            break;
    }
    }
    count++;
    printf("%5d\nNumber of hailstone generated: %d",n,count);

}